name: Auto-Fix Tagged Issue with OpenHands
on:
  issues:
    types: [labeled, opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled]

jobs:
  resolve:
    if: |
      (github.event_name == 'issues' && contains(join(github.event.issue.labels.*.name, ','), 'fix-me')) ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@openhands-agent')) ||
      (github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'fix-me'))
    runs-on: ${{ vars.TARGET_RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Run OpenHands Resolver
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /workspace \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            -e ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            --entrypoint /bin/bash \
            ghcr.io/all-hands-ai/openhands:latest \
            -c "
              set -e
              echo 'Installing Git...'
              apt-get update && apt-get install -y git
              echo 'Starting OpenHands resolver...'
              python -m openhands.resolver.resolve_issue \
                --selected-repo ${{ github.repository }} \
                --issue-number ${{ github.event.issue.number }} \
                --username ${{ github.actor }} \
                --token ${{ secrets.GITHUB_TOKEN }} \
                --llm-model ${{ vars.LLM_MODEL || 'openai/gpt-5' }} \
                --max-iterations ${{ vars.OPENHANDS_MAX_ITER || 8 }} \
                --output-dir /workspace/openhands-output
              echo 'OpenHands resolver completed'
            "
