name: Auto-Fix Tagged Issue with OpenHands
on:
  issues:
    types: [labeled]  # Only trigger when label is added, not on every edit
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled]

# Global concurrency to prevent OpenAI rate limiting
concurrency:
  group: openhands-global
  cancel-in-progress: false  # Queue them instead of canceling

jobs:
  resolve:
    if: |
      (github.event_name == 'issues' && contains(join(github.event.issue.labels.*.name, ','), 'fix-me')) ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@openhands-agent')) ||
      (github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'fix-me'))
    runs-on: ${{ vars.TARGET_RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 60
    concurrency:
      group: openhands-resolver-${{ github.event.issue.number || github.event.pull_request.number }}
      cancel-in-progress: false  # Don't cancel, just queue them
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Run OpenHands Resolver (Docker)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Use PAT if available, otherwise fall back to GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          SANDBOX_VOLUMES: ${{ github.workspace }}:/workspace:rw
          # LLM retry tuning per docs
          LLM_NUM_RETRIES: "4"
          LLM_RETRY_MIN_WAIT: "5"
          LLM_RETRY_MAX_WAIT: "30"
          LLM_RETRY_MULTIPLIER: "2"
        run: |
          docker run --rm --privileged --network host \
            -v ${{ github.workspace }}:/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /workspace \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            -e GITHUB_TOKEN="${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}" \
            -e GH_TOKEN="${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}" \
            -e GITHUB_REPOSITORY="${{ github.repository }}" \
            -e GITHUB_OWNER="${{ github.repository_owner }}" \
            -e GITHUB_API_URL="https://api.github.com" \
            -e LLM_MODEL="${{ vars.LLM_MODEL || 'openai/gpt-4o' }}" \
            -e SANDBOX_VOLUMES="${{ github.workspace }}:/workspace:rw" \
            -e LLM_NUM_RETRIES="${LLM_NUM_RETRIES}" \
            -e LLM_RETRY_MIN_WAIT="${LLM_RETRY_MIN_WAIT}" \
            -e LLM_RETRY_MAX_WAIT="${LLM_RETRY_MAX_WAIT}" \
            -e LLM_RETRY_MULTIPLIER="${LLM_RETRY_MULTIPLIER}" \
            --entrypoint /bin/bash \
            ghcr.io/all-hands-ai/openhands:0.51.1 \
            -lc '
              set -e
              set -x
              export DEBIAN_FRONTEND=noninteractive
              echo "[resolver] installing packages..."
              apt-get update && apt-get install -y --no-install-recommends git tmux curl
              echo "[resolver] packages installed."
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              export TERM=xterm
              # Ensure git config works inside runtime
              # Replace system git with a wrapper to sanitize env for ALL git calls
              if [ -x /usr/bin/git ] && [ ! -x /usr/bin/git.real ]; then mv /usr/bin/git /usr/bin/git.real; fi
              echo "[resolver] installing git wrapper..."
              echo "#!/bin/sh" > /usr/bin/git
              echo "unset GIT_CONFIG GIT_CONFIG_GLOBAL GIT_CONFIG_SYSTEM GIT_CONFIG_NOSYSTEM GIT_CONFIG_COUNT" >> /usr/bin/git
              echo "exec /usr/bin/git.real \"\$@\"" >> /usr/bin/git
              chmod +x /usr/bin/git
              echo "[resolver] git wrapper installed."
              unset GIT_CONFIG GIT_CONFIG_GLOBAL GIT_CONFIG_SYSTEM GIT_CONFIG_NOSYSTEM || true
              git config --global core.pager "" || true
              git config --global --add safe.directory /workspace || true
              git config --global --add safe.directory /workspace/openhands-output/repo || true
              # Fix permissions for OpenHands runtime user UID 42420 to avoid index.lock permission denied
              echo "[resolver] fixing workspace ownership for openhands user..."
              chown -R 42420:42420 /workspace || true
              # Only change directory permissions, not file permissions
              find /workspace -type d -exec chmod 755 {} \; 2>/dev/null || true
              # Create output directory with proper permissions
              mkdir -p /workspace/openhands-output || true
              chown -R 42420:42420 /workspace/openhands-output || true
              echo "[resolver] ensuring playwright browsers..."
              /app/.venv/bin/playwright install chromium || true
              /app/.venv/bin/playwright install-deps chromium || true
              echo "[resolver] playwright ready."
              
              # Add a small delay to help with rate limiting when multiple runs queue up
              echo "[resolver] waiting 10 seconds to avoid rate limit bursts..."
              sleep 10

              # Determine issue number robustly across events
              ISSUE_NUMBER="${{ github.event.issue.number }}"
              if [ -z "${ISSUE_NUMBER}" ]; then ISSUE_NUMBER="${{ github.event.pull_request.number }}"; fi
              if [ -z "${ISSUE_NUMBER}" ]; then echo "ERROR: No issue number found in event payload"; exit 1; fi
              echo "[resolver] issue number: ${ISSUE_NUMBER}"

              # Debug info - safe no secrets
              echo "::group::OpenHands Debug"
              echo "Repo=${GITHUB_REPOSITORY}"
              echo "Owner=${GITHUB_OWNER}"
              echo "Actor=${{ github.actor }}"
              echo "Issue=${ISSUE_NUMBER}"
              echo "Model=${LLM_MODEL}"
              echo "Runtime=local"
              echo "::endgroup::"

              # Verify issue exists via API before launching
              set +e
              curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}" | grep -q "\"number\":"
              CURL_RC=$?
              set -e
              if [ $CURL_RC -ne 0 ]; then echo "ERROR: Issue ${ISSUE_NUMBER} not found via API for ${GITHUB_REPOSITORY}"; exit 1; fi
              echo "[resolver] issue exists via API. launching resolver..."
              # Build optional instructions flag if repository provides one at root
              INSTRUCTIONS_ARGS=""
              if [ -f /workspace/.openhands_instructions ]; then
                INSTRUCTIONS_ARGS="--repo-instruction-file /workspace/.openhands_instructions"
                echo "[resolver] using custom instructions file at /workspace/.openhands_instructions"
              fi
              # Configure git for pushing - ensure proper authentication
              echo "[resolver] configuring git remote with token..."
              git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git || true
              git config --global credential.helper store || true
              echo "https://x-access-token:${GITHUB_TOKEN}@github.com" > ~/.git-credentials || true
              
              env -i \
                OPENAI_API_KEY="${OPENAI_API_KEY}" \
                GITHUB_TOKEN="${GITHUB_TOKEN}" \
                GH_TOKEN="${GH_TOKEN}" \
                GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
                GITHUB_OWNER="${GITHUB_OWNER}" \
                GITHUB_API_URL="${GITHUB_API_URL}" \
                LLM_MODEL="${LLM_MODEL}" \
                SANDBOX_VOLUMES="${SANDBOX_VOLUMES}" \
                PYTHONPATH="/app" \
                VIRTUAL_ENV="/app/.venv" \
                PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
                HOME="/root" \
                TERM="${TERM}" \
                AGENT_CLS="CodeActAgent" \
                /app/.venv/bin/python /app/openhands/resolver/resolve_issue.py \
                --selected-repo ${{ github.repository }} \
                --issue-number ${ISSUE_NUMBER} \
                --username ${{ github.actor }} \
                --token ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }} \
                --llm-model ${{ vars.LLM_MODEL || 'openai/gpt-4o' }} \
                --max-iterations ${{ vars.OPENHANDS_MAX_ITER || 30 }} \
                --output-dir /workspace/openhands-output \
                --runtime local \
                ${INSTRUCTIONS_ARGS}
              RES_RC=$?
              echo "[resolver] resolver exit code: ${RES_RC}"
              echo "[resolver] listing /workspace/openhands-output:"
              ls -la /workspace/openhands-output || true
              echo "[resolver] listing /workspace/openhands-output/repo if exists:"
              ls -la /workspace/openhands-output/repo 2>/dev/null || echo "repo directory not found"
              # With local runtime, no need to inspect Docker containers
              if [ -f /workspace/openhands-output/output.jsonl ]; then
                echo "[resolver] tail output.jsonl:"
                tail -n 200 /workspace/openhands-output/output.jsonl || true
                echo "[resolver] checking what commands the agent ran:"
                grep -o "\"command\":\"[^\"]*\"" /workspace/openhands-output/output.jsonl | tail -n 20 || true
                echo "[resolver] checking for git commands:"
                grep -i "git add\|git commit\|git push" /workspace/openhands-output/output.jsonl | tail -n 10 || true
              else
                echo "[resolver] no output.jsonl present."
              fi
              
              # Check BOTH locations for changes - agent might work in either
              echo "[resolver] checking git status in MAIN workspace /workspace:"
              cd /workspace && git status || true
              
              if [ -d /workspace/openhands-output/repo ]; then
                echo "[resolver] checking git status in cloned repo:"
                cd /workspace/openhands-output/repo && git status || true
                echo "[resolver] checking for untracked files:"
                git status --porcelain || true
                echo "[resolver] listing ALL directories in repo:"
                ls -la || true
                echo "[resolver] searching for any Python files:"
                find . -name "*.py" -type f 2>/dev/null | head -20 || echo "No Python files found"
                echo "[resolver] checking git log for recent commits:"
                git log --oneline -5 || echo "No commits found"
                cd /workspace
              fi
              
              # Also check the main workspace
              echo "[resolver] checking main workspace /workspace:"
              ls -la /workspace/scripts/ 2>/dev/null || echo "No scripts directory in main workspace"
              find /workspace -name "hello_openhands.py" -type f 2>/dev/null | head -5 || true
              
              # Fail if resolver failed
              if [ ${RES_RC} -ne 0 ]; then 
                echo "[resolver] ERROR: Resolver failed with exit code ${RES_RC}"
                exit ${RES_RC}
              fi
              
              # Check if PR was created
              if ! grep -q "\"pull_request\":" /workspace/openhands-output/output.jsonl 2>/dev/null; then
                echo "[resolver] No PR detected in output. Checking if we need to create one..."
                
                # Reset file permissions to avoid including permission changes in PR
                echo "[resolver] Resetting file permissions to avoid unnecessary changes..."
                find /workspace -type f -name "*.py" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.md" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.yml" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.yaml" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.json" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.txt" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.cs" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.csproj" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.ts" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.js" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.html" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.scss" -exec chmod 644 {} \; 2>/dev/null || true
                find /workspace -type f -name "*.css" -exec chmod 644 {} \; 2>/dev/null || true
                git diff --stat || true
                
                # First check the main workspace where agent actually worked
                cd /workspace
                MAIN_HAS_COMMITS=false
                if git log origin/main..HEAD --oneline 2>/dev/null | grep -q .; then
                  echo "[resolver] Found commits in main workspace!"
                  MAIN_HAS_COMMITS=true
                fi
                
                # Also check the cloned repo just in case
                CLONE_HAS_COMMITS=false
                if [ -d /workspace/openhands-output/repo ]; then
                  cd /workspace/openhands-output/repo
                  if git log origin/main..HEAD --oneline 2>/dev/null | grep -q .; then
                    echo "[resolver] Found commits in cloned repo!"
                    CLONE_HAS_COMMITS=true
                  fi
                fi
                
                # Decide which repo to push from
                if [ "${MAIN_HAS_COMMITS}" = "true" ]; then
                  cd /workspace
                  echo "[resolver] Working with main workspace for PR creation"
                elif [ "${CLONE_HAS_COMMITS}" = "true" ]; then
                  cd /workspace/openhands-output/repo
                  echo "[resolver] Working with cloned repo for PR creation"
                else
                  echo "[resolver] No commits found in either location"
                  cd /workspace
                fi
                
                # Check for any commits that have not been pushed
                echo "[resolver] Checking current branch..."
                git branch --show-current
                
                # Check if there are commits not on origin/main
                if git log origin/main..HEAD --oneline 2>/dev/null | grep -q .; then
                    echo "[resolver] Found unpushed commits. Creating PR..."
                    
                    # Create a branch name - always create a new branch for PRs
                    BRANCH_NAME="openhands-fix-issue-${ISSUE_NUMBER}"
                    # Try to create the branch, if it fails we might already be on a branch
                    git checkout -b "${BRANCH_NAME}" 2>/dev/null || true
                    
                    # Configure git for push
                    git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                    
                    # Push the branch
                    echo "[resolver] Pushing branch ${BRANCH_NAME}..."
                    git push -u origin "${BRANCH_NAME}" --force
                    
                    # Create PR using GitHub API
                    echo "[resolver] Creating PR via GitHub API..."
                    curl -X POST \
                      -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls \
                      -d "{
                        \"title\": \"Fix: Issue #${ISSUE_NUMBER}\",
                        \"body\": \"This PR was automatically generated by OpenHands to resolve issue #${ISSUE_NUMBER}\\n\\nCloses #${ISSUE_NUMBER}\",
                        \"head\": \"${BRANCH_NAME}\",
                        \"base\": \"main\"
                      }" | head -n 20
                    
                    echo "[resolver] PR creation completed."
                  else
                    echo "[resolver] No unpushed commits found."
                    git status || true
                  fi
              else
                echo "[resolver] SUCCESS: Pull request created!"
                # Show PR URL
                grep "\"pull_request\":" /workspace/openhands-output/output.jsonl | tail -n 1 || true
              fi
            '
