name: Auto-Fix Tagged Issue with OpenHands
on:
  issues:
    types: [labeled, opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled]

jobs:
  resolve:
    if: |
      (github.event_name == 'issues' && contains(join(github.event.issue.labels.*.name, ','), 'fix-me')) ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@openhands-agent')) ||
      (github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'fix-me'))
    runs-on: ${{ vars.TARGET_RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install OpenHands
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Resolve dependency conflicts proactively
          python -m pip uninstall -y e2b || true
          python -m pip install "e2b>=0.17.1,<0.18.0"
          # Pin to a known working OpenHands build
          python -m pip install --no-cache-dir "openhands-ai==0.9.8"
          
      - name: Configure Docker for OpenHands
        run: |
          # Ensure Docker daemon is running
          sudo systemctl start docker
          sudo usermod -aG docker $USER
          
      - name: Run OpenHands Resolver
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Mount repo into the agent runtime container
          SANDBOX_VOLUMES: ${{ github.workspace }}:/workspace:rw
          # Ensure commits have an identity
          GIT_AUTHOR_NAME: openhands-bot
          GIT_AUTHOR_EMAIL: openhands-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: openhands-bot
          GIT_COMMITTER_EMAIL: openhands-bot@users.noreply.github.com
        run: |
          # Use OpenHands directly on the runner instead of in Docker
          python -m openhands.resolver.resolve_issue \
            --selected-repo ${{ github.repository }} \
            --issue-number ${{ github.event.issue.number }} \
            --username ${{ github.actor }} \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --llm-model ${{ vars.LLM_MODEL || 'openai/gpt-5' }} \
            --max-iterations ${{ vars.OPENHANDS_MAX_ITER || 8 }} \
            --output-dir ./openhands-output
