name: Auto-Fix Tagged Issue with OpenHands
on:
  issues:
    types: [labeled, opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled]

jobs:
  resolve:
    if: |
      (github.event_name == 'issues' && contains(join(github.event.issue.labels.*.name, ','), 'fix-me')) ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@openhands-agent')) ||
      (github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'fix-me'))
    runs-on: ${{ vars.TARGET_RUNNER || 'ubuntu-latest' }}
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Run OpenHands Resolver (Docker)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SANDBOX_VOLUMES: ${{ github.workspace }}:/workspace:rw
          # LLM retry tuning per docs
          LLM_NUM_RETRIES: "4"
          LLM_RETRY_MIN_WAIT: "5"
          LLM_RETRY_MAX_WAIT: "30"
          LLM_RETRY_MULTIPLIER: "2"
        run: |
          docker run --rm --privileged \
            -v ${{ github.workspace }}:/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /workspace \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e LLM_MODEL="${{ vars.LLM_MODEL || 'openai/gpt-5-2025-08-07' }}" \
            -e SANDBOX_VOLUMES="${{ github.workspace }}:/workspace:rw" \
            -e LLM_NUM_RETRIES="${LLM_NUM_RETRIES}" \
            -e LLM_RETRY_MIN_WAIT="${LLM_RETRY_MIN_WAIT}" \
            -e LLM_RETRY_MAX_WAIT="${LLM_RETRY_MAX_WAIT}" \
            -e LLM_RETRY_MULTIPLIER="${LLM_RETRY_MULTIPLIER}" \
            --entrypoint /bin/bash \
            ghcr.io/all-hands-ai/openhands:0.51.1 \
            -lc "
              set -e
              apt-get update && apt-get install -y git
              git config --global user.name 'openhands-bot'
              git config --global user.email 'openhands-bot@users.noreply.github.com'
              /app/.venv/bin/python -m openhands.resolver.resolve_issue \
                --selected-repo ${{ github.repository }} \
                --issue-number ${{ github.event.issue.number }} \
                --username ${{ github.actor }} \
                --token ${{ secrets.GITHUB_TOKEN }} \
                --llm-model ${{ vars.LLM_MODEL || 'openai/gpt-5-2025-08-07' }} \
                --max-iterations ${{ vars.OPENHANDS_MAX_ITER || 8 }} \
                --output-dir /workspace/openhands-output \
                --runtime-container-image ghcr.io/all-hands-ai/runtime:0.51.1-nikolaik
            "
