name: Validate (API + Frontend)
on:
  pull_request:
    types: [opened, synchronize, reopened]

# Prevent multiple validation runs on the same PR
concurrency:
  group: validate-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '9.0.x'
          include-prerelease: false
      - name: Debug .NET Info
        run: |
          dotnet --version
          dotnet --info
          
      - name: Restore & Test
        working-directory: ./src
        run: |
          dotnet restore --verbosity normal
          # Just build for now, fix compilation issues first
          dotnet build --configuration Release --no-restore --verbosity normal
          echo "Build completed. Tests disabled during setup phase."

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - name: Install deps
        working-directory: ./frontend
        run: npm ci
      - name: Lint (if present)
        working-directory: ./frontend
        run: npm run lint --if-present
      - name: Unit tests (if present)
        working-directory: ./frontend
        run: |
          echo "Frontend tests temporarily disabled for setup phase"
          # if [ -f "karma.conf.js" ]; then
          #   npm test --if-present || echo "Tests failed but continuing..."
          # else
          #   echo "No karma.conf.js found, skipping tests"
          # fi

  gate:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: verdict
        with:
          script: |
            const backendResult = '${{ needs.backend.result }}';
            const frontendResult = '${{ needs.frontend.result }}';
            const failed = backendResult !== 'success' || frontendResult !== 'success';
            console.log(`Backend: ${backendResult}, Frontend: ${frontendResult}, Failed: ${failed}`);
            core.setOutput('failed', failed.toString());

      - name: Label PR with fix-me on failure (but not if created by OpenHands)
        if: >-
          ${{
          steps.verdict.outputs.failed == 'true' &&
          !contains(github.event.pull_request.title, 'Fix: Issue #') &&
          !contains(github.event.pull_request.head.ref, 'openhands-fix-issue-')
          }}
        run: gh pr edit "$PR" --add-label "fix-me"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
