name: Validate (API + Frontend)
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - name: Restore & Test
        working-directory: ./src
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test  --configuration Release --no-build --logger trx --collect:"XPlat Code Coverage"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        working-directory: ./frontend
        run: npm ci
      - name: Lint (if present)
        working-directory: ./frontend
        run: npm run lint --if-present
      - name: Unit tests (if present)
        working-directory: ./frontend
        run: |
          if [ -f "karma.conf.js" ]; then
            npx playwright install --with-deps || true
            npx ng test --watch=false --browsers=ChromeHeadless || true
          else
            npm test --if-present
          fi

  gate:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - uses: actions/github-script@v7
        id: verdict
        with:
          script: |
            const failed = ${{ needs.backend.result != 'success' || needs.frontend.result != 'success' }};
            core.setOutput('failed', failed);
      - name: Label PR with fix-me on failure
        if: steps.verdict.outputs.failed == 'true'
        run: gh pr edit "$PR" --add-label "fix-me"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
